const en = {
  app_name: 'Enatega Deliveries Rider App',
  welcome_title: 'Rider Workspace',
  welcome_subtitle: 'Theme, localization, and reusable base components are ready.',
  change_theme: 'Switch theme',
  change_language: 'Switch language',
  current_theme: 'Theme mode: {{mode}}',
  current_language: 'Language: {{language}}',
  auth_title: 'Enter Your Credentials to login',
  auth_subtitle: "We'll check if you have an account",
  auth_email_placeholder: 'Email',
  auth_password_placeholder: 'Password',
  auth_email_required: 'Email is required',
  auth_email_invalid: 'Please enter a valid email',
  auth_password_required: 'Password is required',
  auth_login: 'Login',
  auth_login_loading: 'Logging in...',
  auth_logout: 'Log Out',
  auth_logout_loading: 'Logging out...',

  nav_home: 'Home',
  nav_wallet: 'Wallet',
  nav_earnings: 'Earnings',
  nav_profile: 'Profile',
  wallet_current_balance: 'Current Balance',
  wallet_withdraw_now: 'Withdraw Now',
  wallet_recent_transactions: 'Recent Transactions',
  wallet_no_transactions: 'No transactions found',
  wallet_available_amount: 'Available Amount',
  wallet_enter_amount: 'Enter Amount',
  wallet_confirm_withdraw: 'Confirm Withdraw',
  wallet_withdraw_success_title: 'Your request for withdrawal has been submitted',
  wallet_withdraw_success_subtitle: 'Usually it takes 1-2 business days',

  home_header_title: 'Orders',
  orders_new: 'New Orders',
  orders_processing: 'Processing',
  orders_delivered: 'Delivered',
  status_waiting_for_rider: 'Waiting for rider',
  status_waiting_to_pickup: 'Waiting to pickup',
  status_unknown: 'Unknown',
  order_assign_me: 'Assign me',
  order_assigning: 'Assigning...',
  order_pick_order: 'Pick Order',
  order_delivered: 'Delivered',
  home_status: 'Status',
  home_order_id: 'Order ID',
  home_store_name: 'Hardees Z-Block',
  home_pickup: 'Pickup order',
  home_deliver: 'Deliver Order',
  home_payment_method: 'Payment Method',
  home_order_amount: 'Order Amount',
  home_not_paid: 'Not paid yet',
  home_comment: 'Comment',
  home_comment_text: 'Please bring it to my room',
  orders_empty: 'No orders available',
  order_assigned_title: 'Assigned',
  order_navigate: 'Navigate',
  order_start_navigation: 'Start Navigation to Store',
  order_details_title: 'Order Details',
  order_items_and_quantity: 'ITEMS AND QUANTITY',
  order_price: 'PRICE',
  order_total: 'Total',
  order_delivery_progress: 'Delivery Progress',
  order_status_assigned: 'Assigned',
  order_status_heading_to_store: 'Heading to Store',
  order_status_arrived_at_store: 'Arrived at Store',
  order_status_waiting_for_order: 'Waiting for Order',
  order_status_picked_up: 'Picked Up',
  order_status_out_for_delivery: 'Out for Delivery',
  order_status_arrived_at_customer: 'Arrived at Customer',
  order_status_delivered: 'Delivered',
  order_status_failed: 'Failed',
  order_status_update_to: 'Update to',
  order_status_updating: 'Updating...',

  menu_availability: 'Availability',
  menu_available: 'Available',
  menu_unavailable: 'Unavailable',
  menu_language: 'Language',
  menu_vehicle_type: 'Vehicle Type',
  menu_bank_management: 'Bank Management',
  menu_work_schedule: 'Work schedule',
  menu_profile: 'Profile',
  menu_privacy_policy: 'Privacy Policy',
  menu_about_us: 'About Us',
  menu_help: 'Help',
  menu_logout: 'Logout',
};

export default en;
