const fr = {
  app_name: 'Enatega Deliveries Rider App',
  welcome_title: 'Espace livreur',
  welcome_subtitle: 'Theme, localisation et composants de base reutilisables sont prets.',
  change_theme: 'Changer le thème',
  change_language: 'Changer la langue',
  current_theme: 'Mode de thème: {{mode}}',
  current_language: 'Langue: {{language}}',
  auth_title: 'Entrez vos identifiants pour vous connecter',
  auth_subtitle: 'Nous verifierons si vous avez un compte',
  auth_email_placeholder: 'Email',
  auth_password_placeholder: 'Mot de passe',
  auth_email_required: "L'email est requis",
  auth_email_invalid: 'Veuillez saisir un email valide',
  auth_password_required: 'Le mot de passe est requis',
  auth_login: 'Se connecter',
  auth_login_loading: 'Connexion...',
  auth_logout: 'Se deconnecter',
  auth_logout_loading: 'Deconnexion...',

  nav_home: 'Accueil',
  nav_wallet: 'Portefeuille',
  nav_earnings: 'Gains',
  nav_profile: 'Profil',
  earnings_recent_activity: 'Activite recente',
  earnings_see_more: 'Voir plus',
  earnings_total_earning: 'Gain total',
  earnings_total_earnings: 'Gains totaux',
  earnings_hours: 'Heures',
  earnings_deliveries: 'Livraisons',
  earnings_deliveries_count: 'Livraisons({{count}})',
  earnings_hours_worked: 'Heures travaillees',
  earnings_tips: 'Pourboires',
  earnings_summary: 'Resume',
  earnings_deliveries_empty_title: 'Aucune livraison trouvee',
  earnings_deliveries_empty_subtitle: 'Les livraisons terminees pour cette date apparaitront ici.',

  home_header_title: 'Commandes',
  orders_new: 'Nouvelles',
  orders_processing: 'En cours',
  orders_delivered: 'Livrees',
  status_waiting_for_rider: 'En attente du livreur',
  status_waiting_to_pickup: 'En attente de ramassage',
  status_unknown: 'Inconnu',
  order_assign_me: "M'assigner",
  order_assigning: 'Assignation...',
  order_pick_order: 'Prendre la commande',
  order_delivered: 'Livree',
  home_status: 'Statut',
  home_order_id: 'ID Commande',
  home_store_name: 'Hardees Z-Block',
  home_pickup: 'Recuperer commande',
  home_deliver: 'Livrer commande',
  home_payment_method: 'Methode de paiement',
  home_order_amount: 'Montant de commande',
  home_not_paid: 'Non paye',
  home_comment: 'Commentaire',
  home_comment_text: 'Veuillez le livrer a ma chambre',
  orders_empty: 'Aucune commande disponible',
  order_assigned_title: 'Assigne',
  order_navigate: 'Naviguer',
  order_start_navigation: 'Commencer la navigation vers le magasin',
  order_details_title: 'Details de commande',
  order_items_and_quantity: 'ARTICLES ET QUANTITE',
  order_price: 'PRIX',
  order_total: 'Total',
  order_delivery_progress: 'Progression de livraison',
  order_status_assigned: 'Assigne',
  order_status_heading_to_store: 'En route vers le magasin',
  order_status_arrived_at_store: 'Arrive au magasin',
  order_status_waiting_for_order: 'En attente de commande',
  order_status_picked_up: 'Recupere',
  order_status_out_for_delivery: 'En cours de livraison',
  order_status_arrived_at_customer: 'Arrive chez le client',
  order_status_delivered: 'Livre',
  order_status_failed: 'Echoue',
  order_status_update_to: 'Mettre a jour vers',
  order_status_updating: 'Mise a jour...',

  menu_availability: 'Disponibilite',
  menu_available: 'Disponible',
  menu_unavailable: 'Indisponible',
  menu_language: 'Langue',
  menu_vehicle_type: 'Type de vehicule',
  menu_bank_management: 'Gestion bancaire',
  menu_work_schedule: 'Horaire de travail',
  menu_profile: 'Profil',
  menu_privacy_policy: 'Politique de confidentialite',
  menu_about_us: 'A propos',
  menu_help: 'Aide',
  menu_logout: 'Se deconnecter',
};

export default fr;
